
###
POST http://localhost:3100/signup
Content-Type: application/json

{
    "name": "Alan",
    "email": "AlanFernandes@hotmail.com",
    "password": "irf2009"
    
}

###
POST http://localhost:3100/login
Content-Type: application/json

{

    "email": "AlanFernandes@hotmail.com",
    "password": "irf2009"
    
}

###

POST http://localhost:3100/signup
Content-Type: application/json

{
    "name": "Igor",
    "email": "igorfonseca27@hotmail.com",
    "password": "irf2009"
    
}
###

POST http://localhost:3100/login
Content-Type: application/json

{
    "email": "igorfonseca27@hotmail.com",
    "password": "123456"
    
}
###

DELETE http://localhost:3100/delete
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3M2RmOTEyOWJkYTJlZjA0MmEyZDM1NyIsImlhdCI6MTczMjExNDcwNywiZXhwIjoxNzMyMTE4MzA3fQ.OLpQNTLTQ70qaS0yV3HWpqrUIGf40XqN46Rg2i3ebrQ

{
    "email": "igorfonseca27@hotmail.com"
    
}
###
###

POST http://localhost:3100/refresh-token
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3NDcyMmMwYzM0NGZiYzBkYWJiYmNmOSIsImVtYWlsIjoiaWdvcmZvbnNlY2EyN0Bob3RtYWlsLmNvbSIsImlhdCI6MTczMzkyNjIwOSwiZXhwIjoxNzM0NTMxMDA5fQ.70U-BeX-BMTgWWg-Pto3LVZ6sTpt3d2ciKke_J5IkxA

###
###

POST http://localhost:3100/accessToken
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3NDcyMmMwYzM0NGZiYzBkYWJiYmNmOSIsImVtYWlsIjoiaWdvcmZvbnNlY2EyN0Bob3RtYWlsLmNvbSIsImlhdCI6MTczMzkyNjIwOSwiZXhwIjoxNzM0NTMxMDA5fQ.70U-BeX-BMTgWWg-Pto3LVZ6sTpt3d2ciKke_J5IkxA

###