
###
POST http://localhost:3100/signup
Content-Type: application/json

{
    "name": "Alan",
    "email": "AlanFernandes@hotmail.com",
    "password": "irf2009"
    
}

###
POST http://localhost:3100/login
Content-Type: application/json

{

    "email": "AlanFernandes@hotmail.com",
    "password": "irf2009"
    
}

###

POST http://localhost:3100/signup
Content-Type: application/json

{
    "name": "Igor",
    "email": "igorfonseca27@hotmail.com",
    "password": "irf2009"
    
}
###

POST http://localhost:3100/login
Content-Type: application/json

{
    "email": "igorfonseca27@hotmail.com",
    "password": "123456"
    
}
###

DELETE http://localhost:3100/delete
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3M2RmOTEyOWJkYTJlZjA0MmEyZDM1NyIsImlhdCI6MTczMjExNDcwNywiZXhwIjoxNzMyMTE4MzA3fQ.OLpQNTLTQ70qaS0yV3HWpqrUIGf40XqN46Rg2i3ebrQ

{
    "email": "igorfonseca27@hotmail.com"
    
}
###
###

POST http://localhost:3100/refresh-token
Content-Type: application/json
# credentials: include
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3NDcyMmMwYzM0NGZiYzBkYWJiYmNmOSIsImVtYWlsIjoiaWdvcmZvbnNlY2EyN0Bob3RtYWlsLmNvbSIsImlhdCI6MTczNDYzMDY4MywiZXhwIjoxNzM1MjM1NDgzfQ.SlIdiUplO_oPBNPvDZnw-3W_-OI7vYvDRevy5AEteTE

###
###

POST http://localhost:3100/verifyToken
Content-Type: application/json


###
###

POST http://localhost:3100/signout
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3NDcyMmMwYzM0NGZiYzBkYWJiYmNmOSIsImVtYWlsIjoiaWdvcmZvbnNlY2EyN0Bob3RtYWlsLmNvbSIsImlhdCI6MTczNDQzMTUyNiwiZXhwIjoxNzM1MDM2MzI2fQ.EzU3YiOlOzECs_ZjoXwC0pOqsuWCR8b65KybrLt9nYY

###

PUT http://localhost:3100/updateUserData
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3NzdmNTIyMTNhNGYyOTc0NDNjNjE4ZSIsIm5hbWUiOiJpZ29yIiwiaWF0IjoxNzM2MzQ1MTgyLCJleHAiOjE3MzY5NDk5ODJ9.yFzcGZIuH4BjtuPM__GYXQGqgaDWpalWj2Qc2GCQs34

{
    "name": "igor",
    "lastName": "Fonseca"
}

###