
###
POST http://localhost:3000/form
Content-Type: application/json

{
    "name": "Igor",
    "email": "igorfonseca@gmail.com"
}
###
POST http://localhost:3000/formUpdate
Content-Type: application/json

{
    "emailAtual": "igorfonseca@gmail.com",
    "novoEmail": "igorf@gmail.com"
}
###